// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Note struct {
	ID              int64
	Title           string
	Content         string
	ImageData       string
	CreatedAt       string
	UpdatedAt       string
	DeletedAt       sql.NullString
	EncryptionSalt  []byte
	EncryptionNonce []byte
	IsPinned        bool
	IsEncrypted     bool
}

type NoteTag struct {
	NoteID int64
	TagID  int64
}

type NotesFt struct {
	Title   string
	Content string
}

type Tag struct {
	ID   int64
	Name string
}
