// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const listTags = `-- name: ListTags :many
SELECT tags.name
FROM tags
         JOIN note_tag ON note_tag.tag_id = tags.id
         JOIN notes ON notes.id = note_tag.note_id
WHERE (notes.deleted_at IS NULL OR notes.deleted_at = '')
GROUP BY tags.id, tags.name
ORDER BY LOWER(tags.name), tags.name
`

func (q *Queries) ListTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
