// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (title, content, image_data, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING ID
`

type CreateNoteParams struct {
	Title     string
	Content   string
	ImageData string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.Title,
		arg.Content,
		arg.ImageData,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, title, content, image_data, created_at, updated_at, deleted_at, is_pinned, is_encrypted
FROM notes
WHERE id = ?1 AND (deleted_at IS NULL OR deleted_at = '')
`

type GetNoteByIDRow struct {
	ID          int64
	Title       string
	Content     string
	ImageData   string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   sql.NullString
	IsPinned    bool
	IsEncrypted bool
}

func (q *Queries) GetNoteByID(ctx context.Context, id int64) (GetNoteByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getNoteByID, id)
	var i GetNoteByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.ImageData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsPinned,
		&i.IsEncrypted,
	)
	return i, err
}

const listArchivedNotes = `-- name: ListArchivedNotes :many
SELECT id,
       title,
       content,
       image_data,
       created_at,
       updated_at,
       deleted_at,
       is_pinned,
       is_encrypted
FROM notes
WHERE deleted_at IS NOT NULL
  AND deleted_at != ''
ORDER BY deleted_at DESC
`

type ListArchivedNotesRow struct {
	ID          int64
	Title       string
	Content     string
	ImageData   string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   sql.NullString
	IsPinned    bool
	IsEncrypted bool
}

func (q *Queries) ListArchivedNotes(ctx context.Context) ([]ListArchivedNotesRow, error) {
	rows, err := q.db.QueryContext(ctx, listArchivedNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchivedNotesRow
	for rows.Next() {
		var i ListArchivedNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ImageData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsPinned,
			&i.IsEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT tags.name
FROM tags
         JOIN note_tag ON note_tag.tag_id = tags.id
         JOIN notes ON notes.id = note_tag.note_id
WHERE (notes.deleted_at IS NULL OR notes.deleted_at = '')
GROUP BY tags.id, tags.name
ORDER BY LOWER(tags.name), tags.name
`

func (q *Queries) ListTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByNoteID = `-- name: ListTagsByNoteID :many
SELECT tags.name
FROM tags
         JOIN note_tag ON note_tag.tag_id = tags.id
WHERE note_tag.note_id = ?1
ORDER BY LOWER(tags.name), tags.name
`

func (q *Queries) ListTagsByNoteID(ctx context.Context, noteID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByNoteID, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreNoteByID = `-- name: RestoreNoteByID :execrows
UPDATE notes SET deleted_at = NULL WHERE id = ?
`

func (q *Queries) RestoreNoteByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreNoteByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteNoteByID = `-- name: SoftDeleteNoteByID :execrows
UPDATE notes SET deleted_at = ?1
WHERE id = ?2 AND (deleted_at IS NULL OR deleted_at = '')
`

type SoftDeleteNoteByIDParams struct {
	DeletedAt sql.NullString
	ID        int64
}

func (q *Queries) SoftDeleteNoteByID(ctx context.Context, arg SoftDeleteNoteByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteNoteByID, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
